### ISSUE TITLE
What does this means ? Do I have a loot to claim ?

### ISSUE THREAD

**Issue by darxtrix** [gakonst/lootloose#1]
hey there, 

I can't see anything on my etherscan but the UI is saying I have a loot to claim ? Do I have one ?
<img width="1572" alt="Screenshot 2021-09-03 at 10 17 07 PM" src="https://user-images.githubusercontent.com/5263761/132040987-fad15bbe-a535-4939-aeff-4bba3a44a7bf.png">

**Comment by gakonst** [comment]
Best to open this on the [UI repo](https://github.com/Anish-Agnihotri/lootloose.com/issues), maybe a caching bug. Try hard refreshing!
